### ISSUE TITLE
判断xposed不对

### ISSUE THREAD

**Issue by wanbanjiesan** [153437803/cmake_jnitools#1]
我用小米12和pixel4，在判断路径的时候出错，xposedtool => jni_check_xposed => path = /data/user/0/"xxx"���r��Z,0�@�
还出现乱码，我不确定是否是乱码导致的判断不对

xposedtool => jni_check_xposed => fail, 缓存路径不正确

**Comment by zhxacg** [comment]
自己实现，android多用户路径判断
